### ISSUE TITLE
Script OK, Task not?

### ISSUE THREAD

**Issue by mvevitsis** [thexmanxyz/network-share-reconnecter#5]
The script works for me now (thank you) but the task scheduler task does not.
It gives me a "how would you like to open this file" when the task runs.

**Comment by thexmanxyz** [comment]
@Matvei27 Mhm that's a bit strange never noticed such an error...however I use the same task on three different machines. What OS are u using? The path to the VBS is correct and does not contain blanks?

**Comment by thexmanxyz** [comment]
@Matvei27 Maybe this is your issue: [Task Scheduler](https://social.technet.microsoft.com/Forums/windows/en-US/53d1faa7-1e7e-451c-8080-0a8cc9d532a6/task-scheduler-how-do-you-want-to-open-this-file?forum=w8itprogeneral)

**Comment by thexmanxyz** [comment]
@Matvei27 If the path is Ok and without any blanks and it still doesn't work. You can also try the following Task which I now created. Maybe passing the script path directly to `cscript.exe` solves the issue. 

If this works let's see if we can also remove the annoying terminal. I have another option that also might work by stealthing the command prompt.

[Task.zip](https://github.com/thexmanxyz/network-share-reconnecter/files/1625870/Task.zip)

**Comment by slopsommelier** [comment]
Specifying the path fixed it for me.

**Comment by thexmanxyz** [comment]
@Matvei27 So you don't needed the modified task `xml` and I can close the issue? Otherwise I would've to prepare a second task file or modify the existing one appropriately ;)

**Comment by slopsommelier** [comment]
Nope, all you need to do is specify the path in task scheduler and then only type the script name in the program to open. As on the support page you linked it only gives the error if you chose the full path without specifying the directory.

**Comment by thexmanxyz** [comment]
@Matvei27 Ok i did a small test. You did it like in the screenshot below right?

![grafik](https://user-images.githubusercontent.com/17965908/34905945-6b4709b8-f863-11e7-8428-69c8a48fdd68.png)

Mhm I will think about if i modify the task file if it doesn't work with the full path in the program text field all the time. Maybe it's better to do the separation out of the box or at least specify a note on the project page. Nevertheless it's a weired behaviour that it sometimes works and sometimes not.

**Comment by slopsommelier** [comment]
Yes, it has to be like that.

**Comment by thexmanxyz** [comment]
@Matvei27 Ok thanks, I will simply modify the Task file even if i do not know why this actually happens. But at least it reduces the probability for an error.

**Comment by thexmanxyz** [comment]
fixed with [v1.3.5](https://github.com/thexmanxyz/network-share-reconnecter/releases/download/v1.3.5/nsr.v1.3.5.zip)

/closed
