### ISSUE TITLE
Win7 Import Task Fail : Format Invalid

### ISSUE THREAD

**Issue by AMNegron** [thexmanxyz/network-share-reconnecter#8]
When I try to import task xml, I receive an error.

![image](https://user-images.githubusercontent.com/16216815/43987873-5e98e33e-9cf6-11e8-8874-b570bd77b5a8.png)

Win7 Home Prem:SP1

**Comment by thexmanxyz** [comment]
@AMNegron Sorry for the inconveniences, the version of the release XML file is 1.4 and you need 1.2 for Windows 7. I did a quick rework of the original file. Use this in the meantime until I create the next release which will contain a legacy file. Thanks for reporting!

Here the file you need:

[Network_Share_Reconnecter.zip](https://github.com/thexmanxyz/network-share-reconnecter/files/2280031/Network_Share_Reconnecter.zip)

**Comment by thexmanxyz** [comment]
@AMNegron [v1.3.6](https://github.com/thexmanxyz/network-share-reconnecter/releases/tag/v1.3.6) and [v1.3.7](https://github.com/thexmanxyz/network-share-reconnecter/releases/tag/v1.3.7) released which include a new legacy task file.

/closed
